spring:
  application:
    name: account-manager
  datasource:
    url: jdbc:h2:file:~/acmebankdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialize: true
    data: classpath:import.sql
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
server:
  port: 8000
  servlet:
    context-path: /api
  error:
    include-stacktrace: never

  sql:
    init:
      data-locations: classpath:import.sql
      mode: always
