spring:
  application:
    name: account-manager
  datasource:
    url: jdbc:h2:file:~/acmebankdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    encoding: UTF-8
    locations: classpath:${DATABASE_MIGRATION_PATH:db/migration}
    sql-migration-prefix: V
    sql-migration-separator: __
    baseline-version: ${FLYWAY_BASELINE_VERSION:20240619.001}
    baseline-on-migrate: true
    out-of-order: true
  h2:
    console:
      enabled: true
server:
  port: 8000
  servlet:
    context-path: /api
  error:
    include-stacktrace: never