spring:
  application:
    name: account-manager
  config:
    activate:
      on-profile: default
server:
  port: 8000
  servlet:
    context-path: ${CONTEXT_PATH:/api}
  error:
    include-stacktrace: never
  datasource:
    url: jdbc:h2:file:classpath:acmebankdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;DATABASE_TO_LOWER=TRUE;IFEXISTS=TRUE;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
    settings:
      web-allow-others: false
      trace: true